// const PROVIDER_PREFIX = 'provider';

// export const BIZ_NAME_CHANGED = `${PROVIDER_PREFIX}_BIZ_NAME_CHANGED`;
// export const TAX_ID_CHANGED = `${PROVIDER_PREFIX}_TAX_ID_CHANGED`;
// export const PHOTO_ID_CHANGED = `${PROVIDER_PREFIX}_PHOTO_ID_CHANGED`;
// export const WEBSITE_CHANGED = `${PROVIDER_PREFIX}_WEBSITE_CHANGED`;
// export const YELP_CHANGED = `${PROVIDER_PREFIX}_YELP_CHANGED`;
// export const BIZ_PHONE_CHANGED = `${PROVIDER_PREFIX}_BIZ_PHONE_CHANGED`
// export const CATEGORY_CHANGED = `${PROVIDER_PREFIX}_CATEGORY_CHANGED`;
// export const USER_ID_CHANGED = `${PROVIDER_PREFIX}_USER_ID_CHANGED`;
// export const BIZ_CHANGED = `${PROVIDER_PREFIX}_BIZ_CHANGED`;


