const USER_PREFIX = 'newUSER';

export const FIRST_NAME_CHANGED = `${USER_PREFIX}_FIRST_NAME_CHANGED`;
export const LAST_NAME_CHANGED = `${USER_PREFIX}_LAST_NAME_CHANGED`;
export const EMAIL_CHANGED = `${USER_PREFIX}_EMAIL_CHANGED`;
export const PASSWORD_CHANGED = `${USER_PREFIX}_PASSWORD_CHANGED`;
export const AVATAR_CHANGED = `${USER_PREFIX}_AVATAR_CHANGED`;
export const CELL_NUMBER_CHANGED = `${USER_PREFIX}_CELL_NUMBER_CHANGED`
export const USER_CREATED_FAILED = `${USER_PREFIX}_USER_CREATED_FAILED`;
export const USER_CREATED_SUCCESS = `${USER_PREFIX}_USER_CREATED_SUCCESS`;
export const LOAD_SPINNER = `${USER_PREFIX}_LOAD_SPINNER`;